language: objective-c
before_install:
  - rvm install 2.3.1
  - rvm use 2.3.1
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - gem install cocoapods --pre
  - pod --version

before_script:
  - export QINIU_TEST_ENV="travis"
script:
  - xctool -workspace QiniuSDK.xcworkspace -scheme QiniuSDK_iOS -sdk iphonesimulator -configuration Release test -test-sdk iphonesimulator7.0 -freshInstall -freshSimulator
  - xctool -workspace QiniuSDK.xcworkspace -scheme QiniuSDK_Mac -sdk macosx -configuration Release test -test-sdk macosx
