language: objective-c

rvm:
  - 2.2.0

before_install:
  - gem install cocoapods --pre
  - rm -rf ~/.cocoapods
  - pod setup
  - pod install

before_script:
  - export QINIU_TEST_ENV="travis"

script:
  - xctool -workspace QiniuSDK.xcworkspace -scheme QiniuSDK_iOS -sdk iphonesimulator -configuration Release test -test-sdk iphonesimulator9.0 -freshInstall -freshSimulator
  - xctool -workspace QiniuSDK.xcworkspace -scheme QiniuSDK_Mac -sdk macosx -configuration Release test -test-sdk macosx
