language: objective-c
osx_image: xcode9

before_install:
  - rvm install 2.3.1
  - rvm use 2.3.1
  - brew update
  - gem install cocoapods --pre
  - pod --version
  - pod repo remove master
  - rm -rf ~/.cocoapods
  - pod setup
  - pod install --verbose --no-repo-update

before_script:
  - export QINIU_TEST_ENV="travis"

script:
  - xcodebuild  -workspace QiniuSDK.xcworkspace -scheme QiniuSDK_iOS -configuration Release ARCHS="armv7 armv7s arm64" build
  - xcodebuild  -workspace QiniuSDK.xcworkspace -scheme QiniuSDK_Mac -configuration Release ARCHS="x86_64" build
